/**
 * Cross-application constants shared by the API and the web client.
 * Keep this package dependency-free.
 */
export const API_VERSION = 'v1';
export const API_BASE_PATH = `/api/${API_VERSION}`;

/** HTTP headers understood by the API. */
export const HEADERS = {
  /** Selects the active company (legal entity) for the request. */
  COMPANY_ID: 'x-company-id',
  /** Client-supplied correlation id; generated by the API when absent. */
  CORRELATION_ID: 'x-correlation-id',
  /** Required on all state-changing requests as a CSRF mitigation. */
  REQUESTED_WITH: 'x-requested-with',
  /** Optional idempotency key for financial operations (used from Phase 2). */
  IDEMPOTENCY_KEY: 'idempotency-key',
} as const;

export const REQUESTED_WITH_VALUE = 'XMLHttpRequest';

/** Cookie names issued by the API. Both are httpOnly. */
export const COOKIES = {
  ACCESS_TOKEN: 'acct_access',
  REFRESH_TOKEN: 'acct_refresh',
} as const;
