import { P, PERMISSION_KEYS, type PermissionKey } from './permissions';

/**
 * System roles are seeded for every organization. They are templates that an
 * administrator may later clone/customize; `SUPER_ADMIN` always receives every
 * permission and cannot be edited.
 */
export const SYSTEM_ROLE_KEYS = [
  'SUPER_ADMIN',
  'ACCOUNTING_ADMIN',
  'ACCOUNTANT',
  'FINANCE_MANAGER',
  'AUDITOR',
  'CASHIER',
  'SALES',
  'PURCHASING',
  'INVENTORY',
  'MANAGER',
  'VIEWER',
] as const;

export type SystemRoleKey = (typeof SYSTEM_ROLE_KEYS)[number];

export interface SystemRoleDefinition {
  key: SystemRoleKey;
  name: string;
  description: string;
  permissions: readonly PermissionKey[];
}

/** Every read permission except the audit trail, which is reserved for auditors and administrators. */
const RESTRICTED_VIEWS: readonly PermissionKey[] = [
  'audit.view',
  'integration.view',
  'api-key.view',
  'webhook.view',
];
const VIEW_ALL: PermissionKey[] = PERMISSION_KEYS.filter(
  (k) => k.endsWith('.view') && !RESTRICTED_VIEWS.includes(k),
);
/** Integration platform views (admins, finance managers, auditors). */
const INTEGRATION_VIEWS: PermissionKey[] = ['integration.view', 'api-key.view', 'webhook.view'];

export const SYSTEM_ROLE_DEFINITIONS: readonly SystemRoleDefinition[] = [
  {
    key: 'SUPER_ADMIN',
    name: 'Super Administrator',
    description: 'Full access to every module and setting.',
    permissions: PERMISSION_KEYS,
  },
  {
    key: 'ACCOUNTING_ADMIN',
    name: 'Accounting Administrator',
    description: 'Manages the accounting configuration, periods and users.',
    permissions: [
      ...VIEW_ALL,
      P['audit.view'],
      P['organization.manage'],
      P['company.manage'],
      P['branch.manage'],
      P['user.create'],
      P['user.update'],
      P['user.deactivate'],
      P['role.manage'],
      P['role.assign'],
      P['sod.manage'],
      P['policy.manage'],
      P['numbering.manage'],
      P['import.run'],
      P['opening-balance.manage'],
      P['account.manage'],
      P['journal.create'],
      P['journal.submit'],
      P['journal.approve'],
      P['journal.post'],
      P['journal.reverse'],
      P['period.manage'],
      P['period.close'],
      P['period.reopen'],
      P['period.lock'],
      P['period.post-soft-closed'],
      P['journal.correct'],
      P['recurring-journal.manage'],
      P['prepayment.manage'],
      P['prepayment.post'],
      P['posting-rule.manage'],
      P['integrity.check'],
      P['reconciliation.prepare'],
      P['reconciliation.approve'],
      P['close.manage'],
      P['close.approve'],
      P['tax.manage'],
      P['workflow.manage'],
      P['approval.decide'],
      P['exchange-rate.manage'],
      P['ar-settings.manage'],
      P['customer.credit-manage'],
      P['write-off.approve'],
      P['write-off.post'],
      P['customer-refund.approve'],
      P['ap-settings.manage'],
      P['vendor.approve'],
      P['bill.hold'],
      P['payment-run.approve'],
      P['payment-run.execute'],
      P['ap-accrual.post'],
      ...INTEGRATION_VIEWS,
      P['integration.manage'],
      P['api-key.manage'],
      P['webhook.manage'],
      P['delegation.create'],
      P['delegation.approve'],
      P['delegation.manage'],
      P['attachment.manage'],
      P['ai.use'],
      P['ai.review'],
      P['reports.export'],
    ],
  },
  {
    key: 'ACCOUNTANT',
    name: 'Accountant',
    description: 'Prepares journals, invoices and bills; cannot approve own work.',
    permissions: [
      ...VIEW_ALL,
      P['account.manage'],
      P['import.run'],
      P['opening-balance.manage'],
      P['journal.create'],
      P['reconciliation.prepare'],
      P['close.manage'],
      P['journal.submit'],
      P['recurring-journal.manage'],
      P['payment-run.create'],
      P['bill.hold'],
      P['prepayment.manage'],
      P['invoice.create'],
      P['bill.create'],
      P['customer-payment.create'],
      P['vendor-payment.create'],
      P['customer.manage'],
      P['customer-refund.create'],
      P['write-off.create'],
      P['collection.manage'],
      P['dispute.manage'],
      P['vendor.manage'],
      P['fixed-asset.manage'],
      P['bank-transaction.create'],
      P['bank-statement.import'],
      P['dimension.manage'],
      P['budget.manage'],
      P['expense-claim.create'],
      P['exchange-rate.manage'],
      P['intercompany.post'],
      P['attachment.manage'],
      P['ai.use'],
      P['ai.review'],
      P['reports.export'],
    ],
  },
  {
    key: 'FINANCE_MANAGER',
    name: 'Finance Manager',
    description: 'Approves and posts financial documents; closes periods.',
    permissions: [
      ...VIEW_ALL,
      P['journal.approve'],
      P['journal.post'],
      P['journal.reverse'],
      P['invoice.approve'],
      P['invoice.post'],
      P['invoice.void'],
      P['bill.approve'],
      P['bill.post'],
      P['bill.void'],
      P['bill.match-review'],
      P['vendor-payment.approve'],
      P['vendor-payment.post'],
      ...INTEGRATION_VIEWS,
      P['integration.manage'],
      P['delegation.create'],
      P['delegation.approve'],
      P['customer-payment.approve'],
      P['customer-payment.post'],
      P['customer.credit-manage'],
      P['customer-refund.approve'],
      P['customer-refund.pay'],
      P['write-off.approve'],
      P['write-off.post'],
      P['collection.manage'],
      P['dispute.manage'],
      P['ar-settings.manage'],
      P['ap-settings.manage'],
      P['vendor.approve'],
      P['bill.hold'],
      P['payment-run.create'],
      P['payment-run.approve'],
      P['payment-run.execute'],
      P['ap-accrual.post'],
      P['sales-order.approve'],
      P['sales-return.approve'],
      P['purchase-request.approve'],
      P['purchase-order.approve'],
      P['purchase-return.approve'],
      P['purchasing-settings.manage'],
      P['inventory.post'],
      P['inventory-settings.manage'],
      P['fixed-asset.post'],
      P['bank-transaction.post'],
      P['bank-statement.import'],
      P['period.close'],
      P['period.post-soft-closed'],
      P['journal.correct'],
      P['recurring-journal.manage'],
      P['prepayment.manage'],
      P['prepayment.post'],
      P['posting-rule.manage'],
      P['integrity.check'],
      P['reconciliation.prepare'],
      P['reconciliation.approve'],
      P['close.manage'],
      P['close.approve'],
      P['budget.manage'],
      P['budget.approve'],
      P['expense-claim.create'],
      P['expense-claim.approve'],
      P['expense-claim.post'],
      P['tax.manage'],
      P['exchange-rate.manage'],
      P['fx.revalue'],
      P['intercompany.post'],
      P['approval.decide'],
      P['workflow.manage'],
      P['attachment.manage'],
      P['ai.use'],
      P['ai.review'],
      P['depreciation.run'],
      P['bank-reconciliation.perform'],
      P['reports.export'],
    ],
  },
  {
    key: 'AUDITOR',
    name: 'Auditor',
    description: 'Read-only access to all records including the audit trail.',
    permissions: [
      ...VIEW_ALL,
      ...INTEGRATION_VIEWS,
      P['audit.view'],
      P['reports.export'],
      P['integrity.check'],
    ],
  },
  {
    key: 'CASHIER',
    name: 'Cashier',
    description: 'Records customer receipts and bank transactions.',
    permissions: [
      P['customer.view'],
      P['invoice.view'],
      P['customer-payment.create'],
      P['customer-payment.post'],
      P['bank-account.view'],
      P['bank-transaction.create'],
    ],
  },
  {
    key: 'SALES',
    name: 'Sales',
    description: 'Manages customers, quotations, orders and invoices.',
    permissions: [
      P['customer.view'],
      P['customer.manage'],
      P['invoice.view'],
      P['invoice.create'],
      P['quotation.view'],
      P['quotation.create'],
      P['sales-order.view'],
      P['sales-order.create'],
      P['sales-return.view'],
      P['sales-return.create'],
      P['delivery.view'],
      P['delivery.manage'],
      P['collection.view'],
      P['collection.manage'],
      P['dispute.manage'],
      P['product.view'],
      P['inventory.view'],
    ],
  },
  {
    key: 'PURCHASING',
    name: 'Purchasing',
    description: 'Manages vendors, purchase orders and bills.',
    permissions: [
      P['vendor.view'],
      P['vendor.manage'],
      P['bill.view'],
      P['bill.create'],
      P['purchase-request.view'],
      P['purchase-request.create'],
      P['purchase-order.view'],
      P['purchase-order.create'],
      P['goods-receipt.view'],
      P['goods-receipt.create'],
      P['purchase-return.view'],
      P['purchase-return.create'],
      P['bill.hold'],
      P['payment-run.view'],
      P['product.view'],
      P['inventory.view'],
    ],
  },
  {
    key: 'INVENTORY',
    name: 'Inventory',
    description: 'Manages products, warehouses and stock movements.',
    permissions: [
      P['product.view'],
      P['product.manage'],
      P['inventory.view'],
      P['inventory.adjust'],
      P['inventory.post'],
      P['warehouse.manage'],
      P['goods-receipt.view'],
      P['goods-receipt.create'],
      P['purchase-order.view'],
    ],
  },
  {
    key: 'MANAGER',
    name: 'Manager',
    description: 'Reviews reports and approves operational documents.',
    permissions: [
      ...VIEW_ALL,
      P['invoice.approve'],
      P['bill.approve'],
      P['bill.match-review'],
      P['sales-order.approve'],
      P['sales-return.approve'],
      P['purchase-request.approve'],
      P['purchase-order.approve'],
      P['purchase-return.approve'],
      P['customer-payment.approve'],
      P['customer-refund.approve'],
      P['write-off.approve'],
      P['customer.credit-manage'],
      P['collection.manage'],
      P['vendor.approve'],
      P['bill.hold'],
      P['payment-run.approve'],
      P['reports.export'],
      P['ai.use'],
      P['delegation.create'],
    ],
  },
  {
    key: 'VIEWER',
    name: 'Viewer',
    description: 'Read-only access to reports and master data.',
    permissions: VIEW_ALL,
  },
];
