import { Inject, Injectable } from '@nestjs/common';
import { and, asc, desc, eq, gte, inArray, lte, sql, type SQL } from 'drizzle-orm';
import { Money } from '@accounting/money';
import { P, type AccountType, type PaginatedResult } from '@accounting/types';
import type {
  CreateConsolidationAdjustmentInput,
  CreateConsolidationRunInput,
  ListConsolidationRunsQuery,
} from '@accounting/validation';
import type { AuthenticatedUser } from '@/common/auth/authenticated-user';
import { BusinessRuleError, NotFoundError } from '@/common/errors/app-error';
import { ErrorCodes } from '@/common/errors/error-codes';
import { offsetFor, toPaginatedResult } from '@/common/pagination/pagination';
import { DRIZZLE, type Database, type DbExecutor } from '@/database/database.types';
import {
  accounts,
  consolidationAdjustmentLines,
  consolidationAdjustments,
  consolidationGroups,
  consolidationRuns,
  fiscalPeriods,
  fiscalYears,
  type ConsolidationAdjustment,
  type ConsolidationAdjustmentLine,
  type ConsolidationGroup,
  type ConsolidationRun,
  type ConsolidationRunRates,
  type ConsolidationSnapshotRow,
} from '@/database/schema';
import { GeneralLedgerService } from '@/modules/accounting/ledger/general-ledger.service';
import { DocumentNumberingService } from '@/modules/accounting/numbering/document-numbering.service';
import { AuditService } from '@/modules/audit/audit.service';
import { AuthorityService } from '@/modules/delegations/authority.service';
import { ExchangeRatesService } from '@/modules/fx/exchange-rates.service';
import { OutboxService } from '@/modules/integrations/events/outbox.service';
import { NotificationsService } from '@/modules/integrations/notifications/notifications.service';
import { SodService } from '@/modules/rbac/sod.service';
import { ApprovalsService } from '@/modules/workflows/approvals.service';
import { ConsolidationGroupsService, type MemberView } from './consolidation-groups.service';
import {
  adjustmentTotals,
  averageRate,
  consolidate,
  naturalBalance,
  nciShareOfProfit,
  runEngine,
  translateMember,
  type ChartEntry,
  type ConsolidatedRow,
  type ConsolidatedTotals,
  type MemberInput,
  type StoredAdjustmentLine,
  type TranslatedMember,
} from './consolidation.logic';
import { IntercompanyReconciliationService } from './intercompany-reconciliation.service';

const MODULE = 'CONSOLIDATION';

export interface RunSummary extends ConsolidationRun {
  groupCode: string;
  groupName: string;
  adjustmentCount: number;
}

export interface AdjustmentView extends ConsolidationAdjustment {
  lines: ConsolidationAdjustmentLine[];
  ruleCode: string | null;
}

export interface MemberColumn {
  companyId: string;
  code: string;
  name: string;
  currency: string;
  method: MemberView['method'];
  ownershipPercent: string;
  rates: ConsolidationRunRates[string];
  netIncome: string;
  translationAdjustment: string;
}

export interface RunDetail extends RunSummary {
  presentationCurrency: string;
  groupAccounts: ConsolidationGroup['accounts'];
  members: MemberColumn[];
  adjustments: AdjustmentView[];
  rows: ConsolidatedRow[];
  totals: ConsolidatedTotals & {
    profitAttributableToNci: string;
    profitAttributableToParent: string;
  };
  readiness: Readiness;
}

export interface StatementLine {
  key: string;
  label: string;
  amount: string;
  rows?: ConsolidatedRow[];
}

export interface ConsolidatedStatements {
  runId: string;
  documentNumber: string;
  periodStart: string;
  periodEnd: string;
  currency: string;
  balanceSheet: {
    assets: StatementLine[];
    liabilities: StatementLine[];
    equity: StatementLine[];
    totals: {
      assets: string;
      liabilities: string;
      equity: string;
      nonControllingInterest: string;
      currentEarnings: string;
      liabilitiesAndEquity: string;
      balanced: boolean;
    };
  };
  incomeStatement: {
    revenue: StatementLine[];
    costOfSales: StatementLine[];
    expenses: StatementLine[];
    totals: {
      revenue: string;
      costOfSales: string;
      grossProfit: string;
      expenses: string;
      netIncome: string;
      attributableToNci: string;
      attributableToParent: string;
    };
  };
}

export interface ReadinessItem {
  key: string;
  label: string;
  ok: boolean;
  blocking: boolean;
  detail?: string;
}

export interface Readiness {
  ready: boolean;
  items: ReadinessItem[];
}

/**
 * Consolidation runs (Prompt #9). A run is fiscal-year-to-date for a group:
 * member ledgers are read (never written), translated, and the group's own
 * consolidation ledger (adjustments by account code) is generated by the
 * elimination rules and completed by hand. Finalizing freezes the member
 * figures so the group close is reproducible even if an entity reopens.
 */
@Injectable()
export class ConsolidationRunsService {
  constructor(
    @Inject(DRIZZLE) private readonly db: Database,
    private readonly audit: AuditService,
    private readonly groups: ConsolidationGroupsService,
    private readonly ledger: GeneralLedgerService,
    private readonly rates: ExchangeRatesService,
    private readonly numbering: DocumentNumberingService,
    private readonly approvals: ApprovalsService,
    private readonly authority: AuthorityService,
    private readonly sod: SodService,
    private readonly outbox: OutboxService,
    private readonly notifications: NotificationsService,
    private readonly intercompany: IntercompanyReconciliationService,
  ) {}

  async list(
    organizationId: string,
    query: ListConsolidationRunsQuery,
  ): Promise<PaginatedResult<RunSummary>> {
    const filters: SQL[] = [eq(consolidationGroups.organizationId, organizationId)];
    if (query.groupId) filters.push(eq(consolidationRuns.groupId, query.groupId));
    if (query.status) filters.push(eq(consolidationRuns.status, query.status));
    const where = and(...filters);
    const rows = await this.db
      .select({
        run: consolidationRuns,
        groupCode: consolidationGroups.code,
        groupName: consolidationGroups.name,
        adjustmentCount: sql<number>`(select count(*) from consolidation_adjustments a where a.run_id = ${consolidationRuns.id} and a.status = 'ACTIVE')`,
      })
      .from(consolidationRuns)
      .innerJoin(consolidationGroups, eq(consolidationGroups.id, consolidationRuns.groupId))
      .where(where)
      .orderBy(desc(consolidationRuns.periodEnd), desc(consolidationRuns.documentNumber))
      .limit(query.pageSize)
      .offset(offsetFor(query));
    const [count] = await this.db
      .select({ total: sql<number>`count(*)` })
      .from(consolidationRuns)
      .innerJoin(consolidationGroups, eq(consolidationGroups.id, consolidationRuns.groupId))
      .where(where);
    return toPaginatedResult(
      rows.map((r) => ({
        ...r.run,
        groupCode: r.groupCode,
        groupName: r.groupName,
        adjustmentCount: Number(r.adjustmentCount),
      })),
      Number(count?.total ?? 0),
      query,
    );
  }

  async get(organizationId: string, id: string): Promise<RunDetail> {
    const { run, group } = await this.load(this.db, organizationId, id);
    return this.detail(run, group);
  }

  async create(
    organizationId: string,
    actor: AuthenticatedUser,
    groupId: string,
    input: CreateConsolidationRunInput,
  ): Promise<RunDetail> {
    const id = await this.db.transaction(async (tx) => {
      const group = await this.groups.load(tx, organizationId, groupId);
      if (group.status !== 'ACTIVE')
        throw new BusinessRuleError(
          ErrorCodes.DOCUMENT_INVALID_STATE,
          `Group ${group.code} is inactive.`,
        );
      const periodStart = await this.fiscalYearStart(group.parentCompanyId, input.periodEnd, tx);
      if (input.periodStart && input.periodStart !== periodStart)
        throw new BusinessRuleError(
          ErrorCodes.VALIDATION_FAILED,
          `Consolidation runs are fiscal-year-to-date: the period must start on ${periodStart}.`,
          { periodStart },
        );
      const [clash] = await tx
        .select({ documentNumber: consolidationRuns.documentNumber })
        .from(consolidationRuns)
        .where(
          and(
            eq(consolidationRuns.groupId, groupId),
            eq(consolidationRuns.periodEnd, input.periodEnd),
          ),
        );
      if (clash)
        throw new BusinessRuleError(
          ErrorCodes.DOCUMENT_INVALID_STATE,
          `${clash.documentNumber} already consolidates ${group.code} to ${input.periodEnd}; reopen it instead.`,
        );
      const documentNumber = await this.numbering.allocate(
        group.parentCompanyId,
        'CON',
        Number(input.periodEnd.slice(0, 4)),
        tx,
      );
      const [row] = await tx
        .insert(consolidationRuns)
        .values({
          groupId,
          documentNumber,
          periodStart,
          periodEnd: input.periodEnd,
          currency: group.presentationCurrency,
          description: input.description ?? null,
          rateOverrides: (input.rates ?? {}) as ConsolidationRunRates,
          createdBy: actor.id,
        })
        .returning();
      await this.audit.record(
        {
          action: 'CREATE',
          module: MODULE,
          entityType: 'ConsolidationRun',
          entityId: row!.id,
          newValue: { documentNumber, group: group.code, periodStart, periodEnd: input.periodEnd },
          metadata: { editor: actor.email },
          organizationId,
          companyId: group.parentCompanyId,
        },
        tx,
      );
      return row!.id;
    });
    return this.prepare(organizationId, actor, id);
  }

  /** (Re)generate the rule-driven adjustments and rates from the member ledgers. Manual adjustments are kept. */
  async prepare(organizationId: string, actor: AuthenticatedUser, id: string): Promise<RunDetail> {
    await this.db.transaction(async (tx) => {
      const { run, group } = await this.load(tx, organizationId, id, true);
      this.assertDraft(run);
      const members = await this.activeMembers(group, run, tx);
      const inputs = await this.memberInputs(group, run, members, tx);
      const rates: ConsolidationRunRates = Object.fromEntries(
        inputs.map((m) => [m.companyId, m.rates]),
      );
      const rules = (await this.groups.rules(group.id, tx)).filter((r) => r.active && r.autoApply);
      const chart = await this.chart(group, members, tx);
      const engine = runEngine({
        currency: run.currency,
        translationMethod: group.translationMethod,
        accounts: group.accounts,
        members: inputs,
        rules: rules.map((r) => ({ id: r.id, code: r.code, type: r.type, config: r.config })),
        chart,
      });
      await tx
        .delete(consolidationAdjustments)
        .where(
          and(
            eq(consolidationAdjustments.runId, id),
            eq(consolidationAdjustments.autoGenerated, true),
          ),
        );
      let sequence = await this.nextSequence(tx, id);
      for (const a of engine.adjustments) {
        const totals = adjustmentTotals(a.lines, run.currency);
        const [adj] = await tx
          .insert(consolidationAdjustments)
          .values({
            runId: id,
            sequence: sequence++,
            type: a.type,
            ruleId: a.ruleId,
            companyId: a.companyId,
            description: a.description,
            autoGenerated: true,
            totalDebit: totals.debit,
            totalCredit: totals.credit,
            createdBy: actor.id,
          })
          .returning({ id: consolidationAdjustments.id });
        await tx
          .insert(consolidationAdjustmentLines)
          .values(
            a.lines.map((l, i) => ({
              adjustmentId: adj!.id,
              lineNumber: i + 1,
              companyId: l.companyId,
              accountCode: l.accountCode,
              accountName: l.accountName,
              accountType: l.accountType,
              debit: l.debit,
              credit: l.credit,
              description: l.description,
            })),
          );
      }
      await tx
        .update(consolidationRuns)
        .set({ rates, preparedBy: actor.id, preparedAt: new Date() })
        .where(eq(consolidationRuns.id, id));
      await this.audit.record(
        {
          action: 'UPDATE',
          module: MODULE,
          entityType: 'ConsolidationRun',
          entityId: id,
          newValue: { prepared: true, adjustments: engine.adjustments.length, rates },
          metadata: {
            documentNumber: run.documentNumber,
            editor: actor.email,
            reason: 'Prepared from member ledgers',
          },
          organizationId,
          companyId: group.parentCompanyId,
        },
        tx,
      );
    });
    return this.get(organizationId, id);
  }

  async addAdjustment(
    organizationId: string,
    actor: AuthenticatedUser,
    id: string,
    input: CreateConsolidationAdjustmentInput,
  ): Promise<RunDetail> {
    await this.db.transaction(async (tx) => {
      const { run, group } = await this.load(tx, organizationId, id, true);
      this.assertDraft(run);
      const members = await this.groups.members(group.id, tx);
      const chart = await this.chart(group, members, tx);
      const memberIds = new Set(members.map((m) => m.companyId));
      const lines = input.lines.map((l) => {
        const entry = chart.get(l.accountCode);
        if (!entry)
          throw new BusinessRuleError(
            ErrorCodes.VALIDATION_FAILED,
            `Account ${l.accountCode} does not exist in any member chart.`,
            { accountCode: l.accountCode },
          );
        if (l.companyId && !memberIds.has(l.companyId))
          throw new BusinessRuleError(
            ErrorCodes.VALIDATION_FAILED,
            'Lines can only reference members of the group.',
          );
        return {
          companyId: l.companyId ?? null,
          accountCode: l.accountCode,
          accountName: entry.name,
          accountType: entry.type,
          debit: Money.of(l.debit ?? '0', run.currency).toString(),
          credit: Money.of(l.credit ?? '0', run.currency).toString(),
          description: l.description ?? null,
        };
      });
      const totals = adjustmentTotals(lines, run.currency);
      if (!totals.balanced)
        throw new BusinessRuleError(
          ErrorCodes.JOURNAL_UNBALANCED,
          `Debits ${totals.debit} do not equal credits ${totals.credit}.`,
          totals,
        );
      const sequence = await this.nextSequence(tx, id);
      const [adj] = await tx
        .insert(consolidationAdjustments)
        .values({
          runId: id,
          sequence,
          type: input.type,
          companyId: null,
          description: input.description,
          reference: input.reference ?? null,
          autoGenerated: false,
          totalDebit: totals.debit,
          totalCredit: totals.credit,
          createdBy: actor.id,
        })
        .returning();
      await tx
        .insert(consolidationAdjustmentLines)
        .values(lines.map((l, i) => ({ adjustmentId: adj!.id, lineNumber: i + 1, ...l })));
      await this.audit.record(
        {
          action: 'CREATE',
          module: MODULE,
          entityType: 'ConsolidationAdjustment',
          entityId: adj!.id,
          newValue: {
            run: run.documentNumber,
            sequence,
            type: input.type,
            total: totals.debit,
            description: input.description,
          },
          metadata: { editor: actor.email },
          organizationId,
          companyId: group.parentCompanyId,
        },
        tx,
      );
    });
    return this.get(organizationId, id);
  }

  async voidAdjustment(
    organizationId: string,
    actor: AuthenticatedUser,
    id: string,
    adjustmentId: string,
    reason: string,
  ): Promise<RunDetail> {
    await this.db.transaction(async (tx) => {
      const { run, group } = await this.load(tx, organizationId, id, true);
      this.assertDraft(run);
      const [adj] = await tx
        .select()
        .from(consolidationAdjustments)
        .where(
          and(
            eq(consolidationAdjustments.id, adjustmentId),
            eq(consolidationAdjustments.runId, id),
          ),
        );
      if (!adj) throw new NotFoundError('Consolidation adjustment', adjustmentId);
      if (adj.status === 'VOID') return;
      await tx
        .update(consolidationAdjustments)
        .set({ status: 'VOID', voidReason: reason, voidedBy: actor.id, voidedAt: new Date() })
        .where(eq(consolidationAdjustments.id, adjustmentId));
      await this.audit.record(
        {
          action: 'VOID',
          module: MODULE,
          entityType: 'ConsolidationAdjustment',
          entityId: adjustmentId,
          previousValue: { status: 'ACTIVE' },
          newValue: { status: 'VOID' },
          metadata: { run: run.documentNumber, reason, editor: actor.email },
          organizationId,
          companyId: group.parentCompanyId,
        },
        tx,
      );
    });
    return this.get(organizationId, id);
  }

  /** Four-eyes group close: readiness, workflow, delegable authority, SoD against the preparer, balanced TB, frozen snapshot. */
  async finalize(
    organizationId: string,
    actor: AuthenticatedUser,
    id: string,
    note?: string,
  ): Promise<RunDetail> {
    await this.db.transaction(async (tx) => {
      const { run, group } = await this.load(tx, organizationId, id, true);
      this.assertDraft(run);
      if (!run.preparedAt)
        throw new BusinessRuleError(
          ErrorCodes.CONSOLIDATION_NOT_READY,
          'Prepare the run before finalizing it.',
        );
      const readiness = await this.readiness(
        organizationId,
        group.id,
        run.periodStart,
        run.periodEnd,
        tx,
      );
      const blockers = readiness.items.filter((i) => i.blocking && !i.ok);
      if (blockers.length)
        throw new BusinessRuleError(
          ErrorCodes.CONSOLIDATION_NOT_READY,
          `Group close blocked: ${blockers.map((b) => b.label).join('; ')}.`,
          { blockers },
        );
      const members = await this.activeMembers(group, run, tx);
      const inputs = await this.memberInputs(group, run, members, tx);
      const chart = await this.chart(group, members, tx);
      const translated = inputs
        .filter((m) => m.method !== 'EQUITY')
        .map((m) => translateMember(m, group.translationMethod, run.currency, group.accounts));
      const lines = await this.activeLines(id, tx);
      const tb = consolidate(translated, lines, run.currency, group.accounts, chart);
      if (!tb.totals.balanced)
        throw new BusinessRuleError(
          ErrorCodes.JOURNAL_UNBALANCED,
          `The consolidated trial balance is out by ${tb.totals.difference}.`,
          { difference: tb.totals.difference },
        );
      await this.approvals.assertApproved(tx, {
        companyId: group.parentCompanyId,
        documentType: 'CONSOLIDATION_RUN',
        documentId: id,
        documentNumber: run.documentNumber,
        amount: tb.totals.assets,
        currency: run.currency,
        requestedBy: run.preparedBy ?? actor.id,
      });
      const authority = await this.authority.assert(tx, actor, P['consolidation.approve'], {
        companyId: group.parentCompanyId,
        amount: tb.totals.assets,
        currency: run.currency,
        documentType: 'CONSOLIDATION_RUN',
        documentId: id,
        documentNumber: run.documentNumber,
        createdBy: run.preparedBy,
        action: 'Finalized consolidation run',
      });
      await this.sod.checkActorSeparation(
        organizationId,
        [P['consolidation.run'], P['consolidation.approve']],
        run.preparedBy,
        actor.id,
        tx,
        {
          companyId: group.parentCompanyId,
          entityType: 'ConsolidationRun',
          entityId: id,
          documentNumber: run.documentNumber,
        },
      );
      const snapshot: ConsolidationSnapshotRow[] = inputs.flatMap((m) =>
        m.rows.map((r) => ({
          companyId: m.companyId,
          code: r.code,
          name: r.name,
          type: r.type,
          subtype: r.subtype,
          isIntercompany: r.isIntercompany,
          closing: r.closing,
          opening: r.opening,
          period: r.period,
        })),
      );
      await tx
        .update(consolidationRuns)
        .set({
          status: 'FINALIZED',
          snapshot,
          snapshotAt: new Date(),
          finalizedBy: actor.id,
          finalizedAt: new Date(),
          finalizeNote: note ?? null,
        })
        .where(eq(consolidationRuns.id, id));
      await this.audit.record(
        {
          action: 'APPROVE',
          module: MODULE,
          entityType: 'ConsolidationRun',
          entityId: id,
          previousValue: { status: 'DRAFT' },
          newValue: { status: 'FINALIZED', totals: tb.totals },
          metadata: { documentNumber: run.documentNumber, note, ...authority.audit },
          organizationId,
          companyId: group.parentCompanyId,
        },
        tx,
      );
      await this.outbox.enqueue(tx, {
        eventType: 'consolidation.finalized',
        companyId: group.parentCompanyId,
        dedupeKey: `consolidation.finalized:${id}:${Date.now()}`,
        payload: {
          runId: id,
          documentNumber: run.documentNumber,
          group: group.code,
          periodEnd: run.periodEnd,
          currency: run.currency,
          totals: tb.totals,
        },
      });
      await this.notifications.notify(
        {
          organizationId,
          eventType: 'CONSOLIDATION_FINALIZED',
          severity: 'INFO',
          title: `${run.documentNumber} finalized for ${group.name}`,
          body: `Group figures to ${run.periodEnd}: assets ${run.currency} ${tb.totals.assets}, net income ${tb.totals.netIncome}.`,
          link: `/consolidation/runs/${id}`,
          entityType: 'ConsolidationRun',
          entityId: id,
          permission: 'consolidation.view',
          companyId: group.parentCompanyId,
          dedupeKey: `consolidation-finalized:${id}:${Date.now()}`,
        },
        tx,
      );
    });
    return this.get(organizationId, id);
  }

  async reopen(
    organizationId: string,
    actor: AuthenticatedUser,
    id: string,
    reason: string,
  ): Promise<RunDetail> {
    await this.db.transaction(async (tx) => {
      const { run, group } = await this.load(tx, organizationId, id, true);
      if (run.status !== 'FINALIZED')
        throw new BusinessRuleError(
          ErrorCodes.DOCUMENT_INVALID_STATE,
          `${run.documentNumber} is not finalized.`,
        );
      const [later] = await tx
        .select({ documentNumber: consolidationRuns.documentNumber })
        .from(consolidationRuns)
        .where(
          and(
            eq(consolidationRuns.groupId, group.id),
            eq(consolidationRuns.status, 'FINALIZED'),
            sql`${consolidationRuns.periodEnd} > ${run.periodEnd}`,
          ),
        );
      if (later)
        throw new BusinessRuleError(
          ErrorCodes.DOCUMENT_INVALID_STATE,
          `Reopen ${later.documentNumber} first; later group closes build on this one.`,
        );
      await this.authority.assert(tx, actor, P['consolidation.approve'], {
        companyId: group.parentCompanyId,
        documentType: 'CONSOLIDATION_RUN',
        documentId: id,
        documentNumber: run.documentNumber,
        action: 'Reopened consolidation run',
      });
      await tx
        .update(consolidationRuns)
        .set({
          status: 'DRAFT',
          snapshot: null,
          snapshotAt: null,
          reopenedBy: actor.id,
          reopenedAt: new Date(),
          reopenReason: reason,
        })
        .where(eq(consolidationRuns.id, id));
      await this.approvals.cancelFor(tx, 'CONSOLIDATION_RUN', id);
      await this.audit.record(
        {
          action: 'UPDATE',
          module: MODULE,
          entityType: 'ConsolidationRun',
          entityId: id,
          previousValue: { status: 'FINALIZED' },
          newValue: { status: 'DRAFT' },
          metadata: { documentNumber: run.documentNumber, reason, editor: actor.email },
          organizationId,
          companyId: group.parentCompanyId,
        },
        tx,
      );
      await this.outbox.enqueue(tx, {
        eventType: 'consolidation.reopened',
        companyId: group.parentCompanyId,
        dedupeKey: `consolidation.reopened:${id}:${Date.now()}`,
        payload: { runId: id, documentNumber: run.documentNumber, group: group.code, reason },
      });
      await this.notifications.notify(
        {
          organizationId,
          eventType: 'CONSOLIDATION_REOPENED',
          severity: 'WARNING',
          title: `${run.documentNumber} reopened`,
          body: reason,
          link: `/consolidation/runs/${id}`,
          entityType: 'ConsolidationRun',
          entityId: id,
          permission: 'consolidation.approve',
          companyId: group.parentCompanyId,
          dedupeKey: `consolidation-reopened:${id}:${Date.now()}`,
        },
        tx,
      );
    });
    return this.get(organizationId, id);
  }

  async statements(organizationId: string, id: string): Promise<ConsolidatedStatements> {
    const detail = await this.get(organizationId, id);
    const rows = detail.rows.filter((r) => r.consolidated !== '0.0000');
    const c = detail.currency;
    const sum = (list: ConsolidatedRow[]) =>
      list.reduce((m, r) => m.add(Money.of(r.consolidated, c)), Money.zero(c)).toString();
    const section = (type: AccountType | AccountType[]) => {
      const types = Array.isArray(type) ? type : [type];
      const matched = rows.filter((r) => types.includes(r.type));
      const bySubtype = new Map<string, ConsolidatedRow[]>();
      for (const r of matched) {
        const k = r.subtype ?? 'OTHER';
        bySubtype.set(k, [...(bySubtype.get(k) ?? []), r]);
      }
      return [...bySubtype.entries()].map(([key, list]) => ({
        key,
        label: key
          .replace(/_/g, ' ')
          .toLowerCase()
          .replace(/^\w/, (x) => x.toUpperCase()),
        amount: sum(list),
        rows: list,
      }));
    };
    const assets = section('ASSET');
    const liabilities = section('LIABILITY');
    const equity = section('EQUITY');
    const revenue = section(['REVENUE', 'OTHER_INCOME']);
    const costOfSales = section('COST_OF_SALES');
    const expenses = section(['EXPENSE', 'OTHER_EXPENSE']);
    const t = detail.totals;
    // Presentation: the outside shareholders' share of this year's profit sits with non-controlling interest,
    // current earnings show the parent's share. The ledger only carries the NCI reserves entry.
    const nciTotal = Money.of(t.nonControllingInterest, c).add(
      Money.of(t.profitAttributableToNci, c),
    );
    const equityPresented = Money.of(t.equity, c).add(Money.of(t.profitAttributableToNci, c));
    for (const line of equity) {
      const nciRow = line.rows?.find((r) => r.code === detail.groupAccounts.nonControllingInterest);
      if (nciRow) {
        nciRow.consolidated = nciTotal.toString();
        line.amount = sum(line.rows!);
      }
    }
    const liabilitiesAndEquity = Money.of(t.liabilities, c)
      .add(equityPresented)
      .add(Money.of(t.profitAttributableToParent, c))
      .toString();
    return {
      runId: id,
      documentNumber: detail.documentNumber,
      periodStart: detail.periodStart,
      periodEnd: detail.periodEnd,
      currency: c,
      balanceSheet: {
        assets,
        liabilities,
        equity,
        totals: {
          assets: t.assets,
          liabilities: t.liabilities,
          equity: equityPresented.toString(),
          nonControllingInterest: nciTotal.toString(),
          currentEarnings: t.profitAttributableToParent,
          liabilitiesAndEquity,
          balanced: t.balanced,
        },
      },
      incomeStatement: {
        revenue,
        costOfSales,
        expenses,
        totals: {
          revenue: t.revenue,
          costOfSales: t.costOfSales,
          grossProfit: t.grossProfit,
          expenses: t.expenses,
          netIncome: t.netIncome,
          attributableToNci: t.profitAttributableToNci,
          attributableToParent: t.profitAttributableToParent,
        },
      },
    };
  }

  /** Group close readiness: member periods closed, rates loaded, intercompany matched, prior close finalized. */
  async readiness(
    organizationId: string,
    groupId: string,
    periodStart: string,
    periodEnd: string,
    executor: DbExecutor = this.db,
  ): Promise<Readiness> {
    const group = await this.groups.load(executor, organizationId, groupId);
    const members = (await this.groups.members(groupId, executor)).filter(
      (m) =>
        !(m.disposalDate && m.disposalDate < periodStart) &&
        !(m.acquisitionDate && m.acquisitionDate > periodEnd),
    );
    const items: ReadinessItem[] = [];
    // 1. Fiscal periods of every member covering the window are closed (or locked).
    const open: string[] = [];
    for (const m of members) {
      const periods = await executor
        .select({ status: fiscalPeriods.status, name: fiscalPeriods.name })
        .from(fiscalPeriods)
        .where(
          and(
            eq(fiscalPeriods.companyId, m.companyId),
            lte(fiscalPeriods.startDate, periodEnd),
            gte(fiscalPeriods.endDate, periodStart),
          ),
        );
      const notClosed = periods.filter((p) => p.status === 'OPEN' || p.status === 'SOFT_CLOSED');
      if (!periods.length) open.push(`${m.companyCode}: no fiscal periods`);
      else if (notClosed.length)
        open.push(`${m.companyCode}: ${notClosed.map((p) => p.name).join(', ')}`);
    }
    items.push({
      key: 'PERIODS_CLOSED',
      label: 'Member fiscal periods closed',
      ok: open.length === 0,
      blocking: group.requirePeriodsClosed,
      detail: open.length
        ? open.join('; ')
        : `${members.length} member(s) closed through ${periodEnd}`,
    });
    // 2. Exchange rates for every foreign-currency member.
    const missingRates: string[] = [];
    for (const m of members) {
      if (m.currency === group.presentationCurrency) continue;
      try {
        await this.rates.rateFor(
          organizationId,
          m.currency,
          group.presentationCurrency,
          periodEnd,
          executor,
        );
      } catch {
        missingRates.push(`${m.companyCode} (${m.currency})`);
      }
    }
    items.push({
      key: 'RATES_LOADED',
      label: 'Closing rates loaded',
      ok: missingRates.length === 0,
      blocking: true,
      detail: missingRates.length
        ? `Missing ${missingRates.join(', ')} to ${group.presentationCurrency} on ${periodEnd}`
        : undefined,
    });
    // 3. Intercompany balances agree within tolerance.
    const recon = await this.intercompany.reconcile(
      organizationId,
      { asOf: periodEnd, groupId, currency: group.presentationCurrency },
      executor,
    );
    const tolerance = Money.of(group.intercompanyTolerance, group.presentationCurrency);
    const outOfTolerance = recon.entities.filter(
      (e) =>
        Money.of(e.receivableDifference, group.presentationCurrency).abs().greaterThan(tolerance) ||
        Money.of(e.payableDifference, group.presentationCurrency).abs().greaterThan(tolerance),
    );
    items.push({
      key: 'INTERCOMPANY_MATCHED',
      label: 'Intercompany balances agree with the intercompany register',
      ok: outOfTolerance.length === 0,
      blocking: true,
      detail: outOfTolerance.length
        ? outOfTolerance
            .map(
              (e) =>
                `${e.companyCode}: receivable ${e.receivableDifference}, payable ${e.payableDifference}`,
            )
            .join('; ')
        : `${recon.pairs.length} pair(s) reconciled`,
    });
    // 4. The previous group close (earlier period end) is finalized.
    const [previous] = await executor
      .select({
        documentNumber: consolidationRuns.documentNumber,
        status: consolidationRuns.status,
      })
      .from(consolidationRuns)
      .where(
        and(
          eq(consolidationRuns.groupId, groupId),
          sql`${consolidationRuns.periodEnd} < ${periodEnd}`,
        ),
      )
      .orderBy(desc(consolidationRuns.periodEnd))
      .limit(1);
    items.push({
      key: 'PRIOR_RUN_FINALIZED',
      label: 'Earlier consolidation runs finalized',
      ok: !previous || previous.status === 'FINALIZED',
      blocking: false,
      detail: previous
        ? `${previous.documentNumber} is ${previous.status.toLowerCase()}`
        : 'first run for this group',
    });
    // 5. Group posting accounts exist in the parent chart.
    const codes = Object.values(group.accounts);
    const existing = await executor
      .select({ code: accounts.code })
      .from(accounts)
      .where(and(eq(accounts.companyId, group.parentCompanyId), inArray(accounts.code, codes)));
    const missingCodes = codes.filter((c) => !existing.some((e) => e.code === c));
    items.push({
      key: 'GROUP_ACCOUNTS',
      label: 'Group accounts exist in the parent chart',
      ok: missingCodes.length === 0,
      blocking: true,
      detail: missingCodes.length ? `Missing ${missingCodes.join(', ')}` : undefined,
    });
    return { ready: items.every((i) => i.ok || !i.blocking), items };
  }

  // ---------------------------------------------------------------- internals

  /** Member figures read live from the ledgers (what a fresh preparation would freeze). */
  async liveSnapshot(
    group: ConsolidationGroup,
    run: ConsolidationRun,
  ): Promise<ConsolidationSnapshotRow[]> {
    const members = await this.activeMembers(group, run, this.db);
    const inputs = await this.memberInputs(
      group,
      { ...run, status: 'DRAFT', snapshot: null },
      members,
      this.db,
    );
    return inputs.flatMap((m) =>
      m.rows.map((r) => ({
        companyId: m.companyId,
        code: r.code,
        name: r.name,
        type: r.type,
        subtype: r.subtype,
        isIntercompany: r.isIntercompany,
        closing: r.closing,
        opening: r.opening,
        period: r.period,
      })),
    );
  }

  private async detail(run: ConsolidationRun, group: ConsolidationGroup): Promise<RunDetail> {
    const members = await this.activeMembers(group, run, this.db);
    const inputs = await this.memberInputs(group, run, members, this.db);
    const chart = await this.chart(group, members, this.db);
    const translated: TranslatedMember[] = inputs
      .filter((m) => m.method !== 'EQUITY')
      .map((m) => translateMember(m, group.translationMethod, run.currency, group.accounts));
    const adjustments = await this.adjustments(run.id);
    const lines: StoredAdjustmentLine[] = adjustments
      .filter((a) => a.status === 'ACTIVE')
      .flatMap((a) =>
        a.lines.map((l) => ({
          companyId: l.companyId,
          accountCode: l.accountCode,
          accountName: l.accountName,
          accountType: l.accountType as AccountType,
          debit: l.debit,
          credit: l.credit,
        })),
      );
    const tb = consolidate(translated, lines, run.currency, group.accounts, chart);
    const nci = nciShareOfProfit(translated, inputs, run.currency);
    const readiness =
      run.status === 'FINALIZED'
        ? { ready: true, items: [] }
        : await this.readiness(group.organizationId, group.id, run.periodStart, run.periodEnd);
    const byId = new Map(translated.map((t) => [t.companyId, t]));
    return {
      ...run,
      groupCode: group.code,
      groupName: group.name,
      adjustmentCount: adjustments.filter((a) => a.status === 'ACTIVE').length,
      presentationCurrency: group.presentationCurrency,
      groupAccounts: group.accounts,
      members: inputs.map((m) => ({
        companyId: m.companyId,
        code: m.code,
        name: m.name,
        currency: m.currency,
        method: m.method,
        ownershipPercent: m.ownershipPercent,
        rates: m.rates,
        netIncome: (byId.get(m.companyId)?.netIncome ?? Money.zero(run.currency)).toString(),
        translationAdjustment: (
          byId.get(m.companyId)?.translationAdjustment ?? Money.zero(run.currency)
        ).toString(),
      })),
      adjustments,
      rows: tb.rows,
      totals: {
        ...tb.totals,
        profitAttributableToNci: nci.toString(),
        profitAttributableToParent: Money.of(tb.totals.netIncome, run.currency)
          .subtract(nci)
          .toString(),
      },
      readiness,
    };
  }

  private async adjustments(runId: string): Promise<AdjustmentView[]> {
    const rows = await this.db
      .select()
      .from(consolidationAdjustments)
      .where(eq(consolidationAdjustments.runId, runId))
      .orderBy(asc(consolidationAdjustments.sequence));
    if (!rows.length) return [];
    const lines = await this.db
      .select()
      .from(consolidationAdjustmentLines)
      .where(
        inArray(
          consolidationAdjustmentLines.adjustmentId,
          rows.map((r) => r.id),
        ),
      )
      .orderBy(asc(consolidationAdjustmentLines.lineNumber));
    const ruleIds = rows.map((r) => r.ruleId).filter((x): x is string => Boolean(x));
    const rules = ruleIds.length
      ? await this.db.query.eliminationRules.findMany({
          where: (t, ops) => ops.inArray(t.id, ruleIds),
        })
      : [];
    return rows.map((r) => ({
      ...r,
      lines: lines.filter((l) => l.adjustmentId === r.id),
      ruleCode: rules.find((x) => x.id === r.ruleId)?.code ?? null,
    }));
  }

  private async activeLines(runId: string, tx: DbExecutor): Promise<StoredAdjustmentLine[]> {
    const rows = await tx
      .select({ line: consolidationAdjustmentLines })
      .from(consolidationAdjustmentLines)
      .innerJoin(
        consolidationAdjustments,
        eq(consolidationAdjustments.id, consolidationAdjustmentLines.adjustmentId),
      )
      .where(
        and(
          eq(consolidationAdjustments.runId, runId),
          eq(consolidationAdjustments.status, 'ACTIVE'),
        ),
      );
    return rows.map((r) => ({
      companyId: r.line.companyId,
      accountCode: r.line.accountCode,
      accountName: r.line.accountName,
      accountType: r.line.accountType as AccountType,
      debit: r.line.debit,
      credit: r.line.credit,
    }));
  }

  /** Members in the group for the run's window. */
  private async activeMembers(
    group: ConsolidationGroup,
    run: ConsolidationRun,
    executor: DbExecutor,
  ): Promise<MemberView[]> {
    return (await this.groups.members(group.id, executor)).filter(
      (m) =>
        !(m.disposalDate && m.disposalDate < run.periodStart) &&
        !(m.acquisitionDate && m.acquisitionDate > run.periodEnd),
    );
  }

  /** Member figures: live from the ledgers while draft, from the frozen snapshot once finalized. */
  private async memberInputs(
    group: ConsolidationGroup,
    run: ConsolidationRun,
    members: MemberView[],
    executor: DbExecutor,
  ): Promise<MemberInput[]> {
    const organizationId = group.organizationId;
    const currency = group.presentationCurrency;
    const out: MemberInput[] = [];
    for (const m of members) {
      const rates =
        run.status === 'FINALIZED' && run.rates[m.companyId]
          ? run.rates[m.companyId]!
          : await this.memberRates(organizationId, group, run, m, executor);
      let rows: MemberInput['rows'];
      if (run.status === 'FINALIZED' && run.snapshot) {
        rows = run.snapshot
          .filter((r) => r.companyId === m.companyId)
          .map((r) => ({
            code: r.code,
            name: r.name,
            type: r.type as AccountType,
            subtype: r.subtype,
            isIntercompany: r.isIntercompany,
            closing: r.closing,
            opening: r.opening,
            period: r.period,
          }));
      } else {
        const dayBefore = addDays(run.periodStart, -1);
        const [chart, closing, opening, period] = await Promise.all([
          executor
            .select()
            .from(accounts)
            .where(and(eq(accounts.companyId, m.companyId), eq(accounts.isHeader, false))),
          this.ledger.activity({ companyId: m.companyId, to: run.periodEnd }, executor),
          this.ledger.activity({ companyId: m.companyId, to: dayBefore }, executor),
          this.ledger.activity(
            { companyId: m.companyId, from: run.periodStart, to: run.periodEnd },
            executor,
          ),
        ]);
        const pick = (
          list: { accountId: string; debit: string; credit: string }[],
          accountId: string,
          type: AccountType,
        ) => {
          const a = list.find((x) => x.accountId === accountId);
          return a
            ? naturalBalance(
                type,
                Money.of(a.debit, m.currency),
                Money.of(a.credit, m.currency),
              ).toString()
            : '0.0000';
        };
        rows = chart
          .map((a) => ({
            code: a.code,
            name: a.name,
            type: a.type,
            subtype: a.subtype,
            isIntercompany: a.isIntercompany,
            closing: pick(closing, a.id, a.type),
            opening: pick(opening, a.id, a.type),
            period: pick(period, a.id, a.type),
          }))
          .filter((r) => r.closing !== '0.0000' || r.opening !== '0.0000' || r.period !== '0.0000');
      }
      // The parent's investment cost is in the parent's currency; bring it to presentation at its historical rate.
      const parent = members.find((x) => x.isParent);
      const parentRate =
        parent && parent.currency !== currency
          ? await this.rates.rateFor(
              organizationId,
              parent.currency,
              currency,
              m.acquisitionDate ?? run.periodEnd,
              executor,
            )
          : '1';
      out.push({
        companyId: m.companyId,
        code: m.companyCode,
        name: m.companyName,
        currency: m.currency,
        method: m.method,
        ownershipPercent: m.ownershipPercent,
        isParent: m.isParent,
        acquisitionEquity: m.acquisitionEquity,
        investmentCost: Money.of(m.investmentCost, parent?.currency ?? currency)
          .convert(currency, parentRate)
          .toString(),
        rates,
        rows,
      });
    }
    return out;
  }

  private async memberRates(
    organizationId: string,
    group: ConsolidationGroup,
    run: ConsolidationRun,
    m: MemberView,
    executor: DbExecutor,
  ): Promise<ConsolidationRunRates[string]> {
    const currency = group.presentationCurrency;
    const override: Partial<ConsolidationRunRates[string]> = run.rateOverrides[m.companyId] ?? {};
    if (m.currency === currency)
      return { closing: '1', average: '1', historical: '1', opening: '1' };
    const closing =
      override.closing ??
      (await this.rates.rateFor(organizationId, m.currency, currency, run.periodEnd, executor));
    const opening = await this.rates
      .rateFor(organizationId, m.currency, currency, addDays(run.periodStart, -1), executor)
      .catch(() => closing);
    const average =
      override.average ??
      averageRate(
        await Promise.all(
          monthEnds(run.periodStart, run.periodEnd).map((d) =>
            this.rates
              .rateFor(organizationId, m.currency, currency, d, executor)
              .catch(() => closing),
          ),
        ),
      );
    const historical =
      override.historical ??
      m.historicalRate ??
      (m.acquisitionDate
        ? await this.rates
            .rateFor(organizationId, m.currency, currency, m.acquisitionDate, executor)
            .catch(() => opening)
        : opening);
    return { closing, average, historical, opening };
  }

  /** Account codes -> name / type, parent chart first so group presentation wins. */
  private async chart(
    group: ConsolidationGroup,
    members: MemberView[],
    executor: DbExecutor,
  ): Promise<Map<string, ChartEntry>> {
    const map = new Map<string, ChartEntry>();
    const ids = [
      group.parentCompanyId,
      ...members.map((m) => m.companyId).filter((id) => id !== group.parentCompanyId),
    ];
    for (const companyId of ids) {
      const rows = await executor
        .select({
          code: accounts.code,
          name: accounts.name,
          type: accounts.type,
          subtype: accounts.subtype,
        })
        .from(accounts)
        .where(eq(accounts.companyId, companyId));
      for (const r of rows)
        if (!map.has(r.code)) map.set(r.code, { name: r.name, type: r.type, subtype: r.subtype });
    }
    return map;
  }

  private async fiscalYearStart(
    companyId: string,
    to: string,
    executor: DbExecutor,
  ): Promise<string> {
    const [year] = await executor
      .select({ startDate: fiscalYears.startDate })
      .from(fiscalYears)
      .where(
        and(
          eq(fiscalYears.companyId, companyId),
          lte(fiscalYears.startDate, to),
          gte(fiscalYears.endDate, to),
        ),
      );
    return year?.startDate ?? `${to.slice(0, 4)}-01-01`;
  }

  private async nextSequence(tx: DbExecutor, runId: string): Promise<number> {
    const [row] = await tx
      .select({ max: sql<number>`coalesce(max(${consolidationAdjustments.sequence}), 0)` })
      .from(consolidationAdjustments)
      .where(eq(consolidationAdjustments.runId, runId));
    return Number(row?.max ?? 0) + 1;
  }

  private assertDraft(run: ConsolidationRun): void {
    if (run.status !== 'DRAFT')
      throw new BusinessRuleError(
        ErrorCodes.DOCUMENT_INVALID_STATE,
        `${run.documentNumber} is finalized; reopen it to change it.`,
      );
  }

  private async load(
    executor: DbExecutor,
    organizationId: string,
    id: string,
    lock = false,
  ): Promise<{ run: ConsolidationRun; group: ConsolidationGroup }> {
    const base = executor
      .select({ run: consolidationRuns, group: consolidationGroups })
      .from(consolidationRuns)
      .innerJoin(consolidationGroups, eq(consolidationGroups.id, consolidationRuns.groupId))
      .where(
        and(eq(consolidationRuns.id, id), eq(consolidationGroups.organizationId, organizationId)),
      );
    const [row] = lock ? await base.for('update', { of: consolidationRuns }) : await base;
    if (!row) throw new NotFoundError('Consolidation run', id);
    return row;
  }
}

function addDays(date: string, days: number): string {
  const d = new Date(date + 'T00:00:00Z');
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

/** Month-end dates inside the window plus the window end itself (deduplicated). */
function monthEnds(from: string, to: string): string[] {
  const out: string[] = [];
  let [y, m] = from.split('-').map(Number) as [number, number];
  for (;;) {
    const end = new Date(Date.UTC(y, m, 0)).toISOString().slice(0, 10);
    if (end > to) break;
    if (end >= from) out.push(end);
    m += 1;
    if (m > 12) {
      m = 1;
      y += 1;
    }
  }
  if (!out.includes(to)) out.push(to);
  return out;
}
