/* Response shapes of the group consolidation platform (Prompt #9). Mirrors the API views. */
import type {
  ConsolidationAdjustmentStatus,
  ConsolidationAdjustmentType,
  ConsolidationGroupAccounts,
  ConsolidationGroupStatus,
  ConsolidationMethod,
  ConsolidationRunStatus,
  EliminationRuleConfig,
  EliminationRuleType,
  IntercompanyMatchStatus,
  TranslationMethod,
} from '@accounting/types';
import type { IntegrityFinding } from './receivables-types';

export interface GroupMember {
  id: string;
  groupId: string;
  companyId: string;
  companyCode: string;
  companyName: string;
  currency: string;
  isParent: boolean;
  method: ConsolidationMethod;
  ownershipPercent: string;
  acquisitionDate: string | null;
  disposalDate: string | null;
  acquisitionEquity: string;
  investmentCost: string;
  historicalRate: string | null;
  sortOrder: number;
  notes: string | null;
}

export interface EliminationRule {
  id: string;
  groupId: string;
  code: string;
  name: string;
  type: EliminationRuleType;
  description: string | null;
  autoApply: boolean;
  active: boolean;
  config: EliminationRuleConfig;
  createdAt: string;
}

export interface AccountMappingView {
  id: string;
  accountId: string;
  accountCode: string;
  accountName: string;
  accountType: string;
  groupAccountCode: string;
  groupAccountName: string | null;
  notes: string | null;
}

export interface AccountMappingsView {
  companyId: string;
  mappings: AccountMappingView[];
  unmatched: Array<{ accountId: string; code: string; name: string; type: string }>;
  targets: Array<{ code: string; name: string; type: string }>;
}

export interface ConsolidationGroup {
  id: string;
  code: string;
  name: string;
  status: ConsolidationGroupStatus;
  parentCompanyId: string;
  parentCompanyCode: string;
  parentCompanyName: string;
  presentationCurrency: string;
  translationMethod: TranslationMethod;
  intercompanyTolerance: string;
  requirePeriodsClosed: boolean;
  accounts: ConsolidationGroupAccounts;
  notes: string | null;
  members: GroupMember[];
  rules: EliminationRule[];
  runCount: number;
  createdAt: string;
}

export interface MemberRates {
  closing: string;
  average: string;
  historical: string;
  opening: string;
}

export interface RunMember {
  companyId: string;
  code: string;
  name: string;
  currency: string;
  method: ConsolidationMethod;
  ownershipPercent: string;
  rates: MemberRates;
  netIncome: string;
  translationAdjustment: string;
}

export interface AdjustmentLine {
  id: string;
  lineNumber: number;
  companyId: string | null;
  accountCode: string;
  accountName: string;
  accountType: string;
  debit: string;
  credit: string;
  description: string | null;
}

export interface ConsolidationAdjustment {
  id: string;
  runId: string;
  sequence: number;
  type: ConsolidationAdjustmentType;
  status: ConsolidationAdjustmentStatus;
  ruleId: string | null;
  ruleCode: string | null;
  companyId: string | null;
  description: string;
  reference: string | null;
  autoGenerated: boolean;
  totalDebit: string;
  totalCredit: string;
  voidReason: string | null;
  lines: AdjustmentLine[];
  createdAt: string;
}

export interface ConsolidatedRow {
  code: string;
  name: string;
  type: string;
  subtype: string | null;
  isIntercompany: boolean;
  byCompany: Record<string, string>;
  combined: string;
  adjustments: string;
  consolidated: string;
}

export interface ReadinessItem {
  key: string;
  label: string;
  ok: boolean;
  blocking: boolean;
  detail?: string;
}

export interface Readiness {
  ready: boolean;
  items: ReadinessItem[];
}

export interface ConsolidationRunSummary {
  id: string;
  groupId: string;
  groupCode: string;
  groupName: string;
  documentNumber: string;
  status: ConsolidationRunStatus;
  periodStart: string;
  periodEnd: string;
  currency: string;
  description: string | null;
  adjustmentCount: number;
  preparedAt: string | null;
  finalizedAt: string | null;
  finalizeNote: string | null;
  reopenedAt: string | null;
  reopenReason: string | null;
  snapshotAt: string | null;
  createdAt: string;
}

export interface ConsolidationRun extends ConsolidationRunSummary {
  presentationCurrency: string;
  groupAccounts: ConsolidationGroupAccounts;
  members: RunMember[];
  adjustments: ConsolidationAdjustment[];
  rows: ConsolidatedRow[];
  totals: {
    assets: string;
    liabilities: string;
    equity: string;
    revenue: string;
    costOfSales: string;
    grossProfit: string;
    expenses: string;
    netIncome: string;
    nonControllingInterest: string;
    translationAdjustment: string;
    difference: string;
    balanced: boolean;
    profitAttributableToNci: string;
    profitAttributableToParent: string;
  };
  readiness: Readiness;
}

export interface StatementLine {
  key: string;
  label: string;
  amount: string;
  rows?: ConsolidatedRow[];
}

export interface ConsolidatedStatements {
  runId: string;
  documentNumber: string;
  periodStart: string;
  periodEnd: string;
  currency: string;
  balanceSheet: {
    assets: StatementLine[];
    liabilities: StatementLine[];
    equity: StatementLine[];
    totals: {
      assets: string;
      liabilities: string;
      equity: string;
      nonControllingInterest: string;
      currentEarnings: string;
      liabilitiesAndEquity: string;
      balanced: boolean;
    };
  };
  incomeStatement: {
    revenue: StatementLine[];
    costOfSales: StatementLine[];
    expenses: StatementLine[];
    totals: {
      revenue: string;
      costOfSales: string;
      grossProfit: string;
      expenses: string;
      netIncome: string;
      attributableToNci: string;
      attributableToParent: string;
    };
  };
}

export interface IntercompanyPair {
  fromCompanyId: string;
  fromCompanyCode: string;
  toCompanyId: string;
  toCompanyCode: string;
  count: number;
  owed: string;
  owedCurrency: string;
  receivable: string;
  receivableCurrency: string;
  owedPresentation: string;
  receivablePresentation: string;
  difference: string;
  status: IntercompanyMatchStatus;
}

export interface IntercompanyEntity {
  companyId: string;
  companyCode: string;
  currency: string;
  receivableLedger: string;
  payableLedger: string;
  receivableExpected: string;
  payableExpected: string;
  receivableDifference: string;
  payableDifference: string;
}

export interface IntercompanyReconciliation {
  asOf: string;
  currency: string;
  pairs: IntercompanyPair[];
  entities: IntercompanyEntity[];
  totals: { openTransactions: string; unmatchedPairs: number; entitiesWithDrift: number };
}

export interface ConsolidationIntegrityReport {
  asOf: string;
  currency: string;
  ranAt: string;
  status: 'OK' | 'WARNING' | 'CRITICAL';
  findings: IntegrityFinding[];
}
